### ISSUE TITLE
Missing binaries

### ISSUE THREAD

**Issue by nikolay** [siderolabs/conform#263]
The latest pre-release of `v0.1.0-alpha.30` has no binaries and thus cannot be installed via [Aqua](https://aquaproj.github.io/).

**Comment by frezbo** [comment]
It did have the binaries, just not marked as a pre-release, see https://github.com/siderolabs/conform/releases/tag/v0.1.0-alpha.30

**Comment by nikolay** [comment]
@frezbo Thank you! I swear, it failed, there was only source archives, but now it's all good and Aqua installs it. Maybe a GitHub glitch?
